version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app